 server:
   port: 8081
 spring:
   datasource:
     password: postgres
     url: jdbc:postgresql://localhost:5432/hotelapi
     username: postgres
   jpa:
     hibernate:
       ddl-auto: create-drop
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         format_sql: true
     show-sql: true

 application:
    jwt:
      secretKey: vsdlövsdvsdvvsdkvlkdfklvkldfklkafbafreiutuhybpdopvofaopvoadbgrjbjrowfi2€%##%%#)TJIgie@@2dcscdsvdfvfdvfdvdgjsdc
      tokenPrefix: 'Bearer '
      tokenExpirationAfterDays: 10

